Added clarification on how maintenance fee is paid
Atlantis-PBEM/Atlantis pull request #111
Opened 2022-02-21 18:18 UTC by rmstdope

Added a priority list of how the maintenance fee is paid for a unit. Addresses issue #109.

2022-02-24 14:22 UTC, Elfinhope commented
Yes it looks like this resolves the issue.  Thanks.  I haven't had time to research the issue and get a fix put together.

2022-09-23 13:23 UTC, valdisz requested changes

2022-09-23 13:23 UTC, valdisz commented on genrules.cpp
> +		temp = "In summary, the order of priority for how the maintenance fee is paid "
I think `Here is how the maintenance fee is paid:` would be better. But still, there is the passive voice...

2024-05-07 07:32 UTC, jt-traub commented
Pulled into PR#189.  Closing

2024-05-07 07:33 UTC, closed without merging